apiVersion: apps/v1
kind: Deployment
metadata:
  name: building-api-deployment
  namespace: uvasds-services
  labels:
    app: building-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: building-api
  template:
    metadata:
      labels:
        app: building-api
    spec:
      containers:
      - name: building-api-container
        image: ghcr.io/uvads/building-api:{{ .Values.version.buildingApi }}
        env:
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: dp1pass
              key: DBPASS
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: building-api-ingress
  namespace: uvasds-services
spec:
  rules:
  - host: sds-building-api.pods.uvarc.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: building-service
            port:
              number: 8080
  - host: building-api.uvasds.sh
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: building-service
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: building-service
  namespace: uvasds-services
spec:
  selector:
    app: building-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
